#!/usr/bin/env bash
# scan-stubs.sh — scan codebase for stubs, fake implementations, and unfinished integrations
# Creates todo/US-NNN.md items for any findings.
#
# Usage:
#   bash scan-stubs.sh              # scan and create todos
#   bash scan-stubs.sh --dry-run    # scan only, print findings, create nothing
#   bash scan-stubs.sh --ai         # scan then pass findings to Claude for deeper analysis
#
# Designed to be run on demand or as a cron job:
#   0 9 * * 1 bash /path/to/sefiathome/scan-stubs.sh >> /path/to/scan-stubs.log 2>&1

set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")" && pwd)"
SRC_DIR="$REPO_DIR/src"
TODO_DIR="$REPO_DIR/todo"
SCAN_LOG="$REPO_DIR/scan-stubs.log"

DRY_RUN=false
AI_ANALYSIS=false

for arg in "$@"; do
    case $arg in
        --dry-run) DRY_RUN=true ;;
        --ai)      AI_ANALYSIS=true ;;
    esac
done

echo "=== scan-stubs.sh $(date '+%Y-%m-%d %H:%M:%S') ===" | tee -a "$SCAN_LOG"

# ---------------------------------------------------------------------------
# 1. Grep for stub patterns in src/ (exclude __pycache__ and .pyc)
# ---------------------------------------------------------------------------

TMPFILE=$(mktemp)
trap 'rm -f "$TMPFILE"' EXIT

grep -rn --include="*.py" \
    -e "TODO" \
    -e "FIXME" \
    -e "HACK" \
    -e "raise NotImplementedError" \
    -e "#.*\bstub\b" \
    -e "#.*\bfake\b" \
    -e "#.*\bplaceholder\b" \
    -e "#.*not implemented" \
    "$SRC_DIR" 2>/dev/null \
    | grep -v "__pycache__" \
    > "$TMPFILE" || true

# Also catch bare ellipsis function bodies (def foo(): ...)
grep -rn --include="*.py" -P "^\s+\.\.\.$" "$SRC_DIR" 2>/dev/null \
    | grep -v "__pycache__" \
    >> "$TMPFILE" || true

# Deduplicate
sort -u "$TMPFILE" -o "$TMPFILE"

TOTAL=$(wc -l < "$TMPFILE" | tr -d ' ')

if [[ "$TOTAL" -eq 0 ]]; then
    echo "No stubs or unimplemented code found in $SRC_DIR" | tee -a "$SCAN_LOG"
    exit 0
fi

echo "Found $TOTAL potential stub/unimplemented lines:" | tee -a "$SCAN_LOG"
cat "$TMPFILE" | tee -a "$SCAN_LOG"
echo "" | tee -a "$SCAN_LOG"

if [[ "$DRY_RUN" == "true" ]]; then
    echo "[DRY RUN] No todo items created." | tee -a "$SCAN_LOG"
    exit 0
fi

# ---------------------------------------------------------------------------
# 2. Optional: AI deep analysis via Claude
# ---------------------------------------------------------------------------

if [[ "$AI_ANALYSIS" == "true" ]]; then
    echo "--- AI Analysis ---" | tee -a "$SCAN_LOG"
    PROMPT="You are a code reviewer. The following grep results show potential stubs, fake implementations, or unfinished integrations in a Python codebase. For each finding, assess whether it is a genuine stub that needs implementation, a legitimate use (e.g. a test mock, a valid NotImplementedError in an abstract base class), or a false positive. Group real stubs by file and summarise what needs to be implemented.\n\nFindings:\n$(cat "$TMPFILE")"
    echo "$PROMPT" | claude --print 2>/dev/null | tee -a "$SCAN_LOG" || echo "[AI analysis unavailable]" | tee -a "$SCAN_LOG"
    echo "" | tee -a "$SCAN_LOG"
fi

# ---------------------------------------------------------------------------
# 3. Group findings by file
# ---------------------------------------------------------------------------

declare -A FILE_FINDINGS
declare -A FILE_LINECOUNT

while IFS= read -r line; do
    [[ -z "$line" ]] && continue
    filepath=$(echo "$line" | cut -d: -f1)
    rest=$(echo "$line" | cut -d: -f2-)
    rel_path="${filepath#$REPO_DIR/}"
    FILE_FINDINGS["$rel_path"]+="  $rest"$'\n'
    FILE_LINECOUNT["$rel_path"]=$(( ${FILE_LINECOUNT["$rel_path"]:-0} + 1 ))
done < "$TMPFILE"

# ---------------------------------------------------------------------------
# 4. Find next available US number (skip any already claimed by scan-stubs)
# ---------------------------------------------------------------------------

find_next_us_num() {
    local max=0
    for f in "$TODO_DIR"/US-*.md; do
        [[ -f "$f" ]] || continue
        local num
        num=$(basename "$f" .md | sed 's/US-0*//' | grep -E '^[0-9]+$' || echo 0)
        [[ "$num" -gt "$max" ]] && max=$num
    done
    echo $((max + 1))
}

# ---------------------------------------------------------------------------
# 5. Check for existing scan-stubs todos to avoid duplicates
# ---------------------------------------------------------------------------

existing_for_file() {
    local rel_path="$1"
    grep -rl "Generated by scan-stubs.sh" "$TODO_DIR"/*.md 2>/dev/null \
        | xargs grep -l "$rel_path" 2>/dev/null \
        | head -1 || true
}

# ---------------------------------------------------------------------------
# 6. Create one todo per affected file
# ---------------------------------------------------------------------------

NEXT_NUM=$(find_next_us_num)
CREATED=0
SKIPPED=0

for rel_path in "${!FILE_FINDINGS[@]}"; do
    # Skip if a scan-stubs todo already exists for this file
    existing=$(existing_for_file "$rel_path")
    if [[ -n "$existing" ]]; then
        echo "SKIP $rel_path — already tracked in $(basename "$existing")" | tee -a "$SCAN_LOG"
        SKIPPED=$((SKIPPED + 1))
        continue
    fi

    US_ID=$(printf "US-%03d" "$NEXT_NUM")
    TODO_FILE="$TODO_DIR/$US_ID.md"

    # Derive component from path: src/sefi/<component>/...
    component=$(echo "$rel_path" | awk -F/ '{print $3}')
    [[ -z "$component" || "$component" == "sefi" ]] && component="core"

    FINDINGS_BLOCK="${FILE_FINDINGS[$rel_path]}"
    COUNT="${FILE_LINECOUNT[$rel_path]}"

    cat > "$TODO_FILE" << EOF
# $US_ID: Resolve stubs/unimplemented code in $rel_path

**Status:** unclaimed
**Model:** sonnet
**Component:** $component
**Depends On:** None
**Traces To:** (scan-stubs.sh)

## Description

Stub scanner found $COUNT unimplemented item(s), TODO comment(s), or fake integration(s)
in \`$rel_path\`. Review each finding: implement, remove, or convert to a tracked decision.

## Findings

\`\`\`
$FINDINGS_BLOCK
\`\`\`

## Acceptance Criteria

- [ ] All TODO/FIXME comments resolved or converted to tracked issues
- [ ] No \`raise NotImplementedError\` in production code paths
- [ ] No stub or fake implementations left in non-test modules
- [ ] No bare ellipsis (\`...\`) function bodies in production code
- [ ] Tests pass after changes

## Notes

Generated by scan-stubs.sh on $(date '+%Y-%m-%d').
Review findings carefully — some may be legitimate (abstract base classes, test helpers).
EOF

    echo "Created $TODO_FILE ($COUNT finding(s) in $rel_path)" | tee -a "$SCAN_LOG"
    NEXT_NUM=$((NEXT_NUM + 1))
    CREATED=$((CREATED + 1))
done

echo "" | tee -a "$SCAN_LOG"
echo "Done. Created: $CREATED todo(s). Skipped (already tracked): $SKIPPED." | tee -a "$SCAN_LOG"

if [[ "$CREATED" -gt 0 ]]; then
    echo "Review new items in $TODO_DIR/ and update todo/SUMMARY.md." | tee -a "$SCAN_LOG"
fi
